In [9]:
from mu2e import mu2e_ext_path
from root_pandas import read_root
import pandas as pd
from ROOT import TFile

In [63]:
tf_with_dot = TFile.Open(mu2e_ext_path+'datafiles/BTrk/val_trkana_with_dot.root')
tf_no_dot = TFile.Open(mu2e_ext_path+'datafiles/BTrk/val_trkana_stable.root')

In [73]:
print 'File with trailing period'
print tf_with_dot.Get('TrkAna').Get('trkana').Scan('evtinfo.eventid:evtinfo.runid:evtinfo.subrunid:evtinfo.evtwt:evtinfo.beamwt:evtinfo.genwt','','"colsize=15',5)
print 'File without trailing period'
print tf_no_dot.Get('TrkAna').Get('trkana').Scan('evtinfo.eventid:evtinfo.runid:evtinfo.subrunid:evtinfo.evtwt:evtinfo.beamwt:evtinfo.genwt','','"colsize=15',5)

File with trailing period
************************************************************************************************************************
*    Row   * evtinfo.eventid *   evtinfo.runid * evtinfo.subruni *   evtinfo.evtwt *  evtinfo.beamwt *   evtinfo.genwt *
************************************************************************************************************************
*        0 *               1 *               1 *               0 *               1 *               1 *               1 *
*        1 *               3 *               1 *               0 *               1 *               1 *               1 *
*        2 *               4 *               1 *               0 *               1 *               1 *               1 *
*        3 *               5 *               1 *               0 *               1 *               1 *               1 *
*        4 *               8 *               1 *               0 *               1 *               1 *               1 *
************************************************************************************************************************
5
File without trailing period
************************************************************************************************************************
*    Row   * evtinfo.eventid *   evtinfo.runid * evtinfo.subruni *   evtinfo.evtwt *  evtinfo.beamwt *   evtinfo.genwt *
************************************************************************************************************************
*        0 *               1 *               1 *               0 *               1 *               1 *               1 *
*        1 *               3 *               1 *               0 *               1 *               1 *               1 *
*        2 *               4 *               1 *               0 *               1 *               1 *               1 *
*        3 *               5 *               1 *               0 *               1 *               1 *               1 *
*        4 *               8 *               1 *               0 *               1 *               1 *               1 *
************************************************************************************************************************
5

In [74]:
df_stable = read_root(mu2e_ext_path+'datafiles/BTrk/val_trkana_stable.root', 'TrkAna/trkana', 'uem')
df_test = read_root(mu2e_ext_path+'datafiles/BTrk/val_trkana_with_dot.root', 'TrkAna/trkana', 'uem.')
#df3 = read_root(mu2e_ext_path+'datafiles/BTrk/val_trkana_test2.root')
#df4 = read_root(mu2e_ext_path+'datafiles/BTrk/val_trkana_test3.root')

In [22]:
def print_full(x):
    pd.set_option('display.max_rows', len(x))
    print(x)
    pd.reset_option('display.max_rows')

In [76]:
print_full(((df_stable == df_test).all()))

ValueError: Can only compare identically-labeled DataFrame objects

In [70]:
df_test.head()

,uem._status,uem._pdg,uem._nhits,uem._ndof,uem._nactive,uem._ndouble,uem._ndactive,uem._nnullambig,uem._nmat,uem._nmatactive,...,uem._d0,uem._p0,uem._om,uem._z0,uem._td,uem._d0err,uem._p0err,uem._omerr,uem._z0err,uem._tderr
0,-1000,32765,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-1000,32765,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-1000,32765,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1000,32765,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-1000,32765,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
df_stable.head()

,uem_status,uem_pdg,uem_nhits,uem_ndof,uem_nactive,uem_ndouble,uem_ndactive,uem_nnullambig,uem_nmat,uem_nmatactive,...,uem_d0,uem_p0,uem_om,uem_z0,uem_td,uem_d0err,uem_p0err,uem_omerr,uem_z0err,uem_tderr
0,-1000,0,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-1000,0,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-1000,0,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1000,0,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-1000,0,-1,-1,-1,-1,-1,-1,-1,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0